Blocked access to external URL http://www1.localhost:8800/cors/resources/preflight.py?token=c43dbed5-a445-438e-81aa-76c0581ca8ad
Blocked access to external URL http://www1.localhost:8800/cors/resources/preflight.py?token=cf0b4a14-deff-4a7c-bb50-c59c290c06b7
Blocked access to external URL http://www1.localhost:8800/cors/resources/preflight.py?token=0aec2fe0-3b83-469e-bfce-b92efc185cdc&max_age=
Blocked access to external URL http://www1.localhost:8800/cors/resources/preflight.py?token=f0036399-1426-481c-b426-6fa04d577a93&max_age=0
Blocked access to external URL http://www1.localhost:8800/cors/resources/preflight.py?token=402298a8-92b1-4024-8cb7-c2dfdaf19f73&max_age=-1
Blocked access to external URL http://www1.localhost:8800/cors/resources/preflight.py?max_age=1&token=13ce2e6c-46f9-4cde-a649-4269cc6ee5d0
Preflight cache


FAIL Test preflight  A network error occurred.
FAIL preflight for x-print should be cached  A network error occurred.
FAIL age = blank, should be cached  A network error occurred.
FAIL age = 0, should not be cached  A network error occurred.
FAIL age = -1, should not be cached  A network error occurred.
FAIL preflight first request, second from cache, wait, third should preflight again assert_unreached: Got unexpected error event on the XHR object Reached unreachable code

