Blocked access to external URL https://www.127.0.0.1:9443/xhr/resources/redirect.py?location=https://localhost:9443/fetch/metadata/resources/record-header.py?file=redirect-multiple-cross-sitee9f0b6b4-eb27-4a53-88d7-c5c6e7f85e0b


Harness Error (TIMEOUT), message = null

TIMEOUT Same-Origin -> Cross-Site -> Same-Origin redirect Test timed out

